services:
  db:
    image: timescale/timescaledb:latest-pg17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8.2
    ports:
      - 6379:6379
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

volumes:
  postgres_data:
  redis_data:
  redis-insight:
